### ISSUE TITLE
Matplotlib should run from the main thread

### ISSUE THREAD

**Issue by kwahoo2** [ArrestedLightning/PyOszi#1]
Hi,

First of all thank you for this work, most things works great on the handheld DSO1062B!

There is a small issue with the raw_data.py example. It tries to run Matplotlib GUI from the callback thread, what causes issues:
```
Received data of length 3000
RMS of data is: 0.5433650735535723
<stdin>:5: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
<stdin>:7: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
Exception in thread Thread-3 (__usb_read_handler):
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adi/programowanie/oscyloskop/PyOszi/PyOszi.py", line 205, in __usb_read_handler
    self.__parse_response(response)
  File "/home/adi/programowanie/oscyloskop/PyOszi/PyOszi.py", line 185, in __parse_response
    self.data_callback(raw_data_float, channel)
  File "<stdin>", line 7, in callback
  File "/usr/lib64/python3.11/site-packages/matplotlib/pyplot.py", line 421, in show
    return _get_backend_mod().show(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/matplotlib/backend_bases.py", line 3554, in show
    cls.mainloop()
  File "/usr/lib64/python3.11/site-packages/matplotlib/backends/backend_qt.py", line 1021, in mainloop
    with _maybe_allow_interrupt(qapp):
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/matplotlib/backends/qt_compat.py", line 233, in _maybe_allow_interrupt
    old_wakeup_fd = signal.set_wakeup_fd(wsock.fileno())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: set_wakeup_fd only works in main thread of the main interpreter
```

I modified the script slightly moving plotting to the main thread (not very elegant), and then plotting works just fine:
```
from PyOszi import *
from time import sleep
from datetime import datetime
import matplotlib
import matplotlib.pyplot as plt
import math

recv_data = []

def callback(data, channel):
    if (data):
        print("Received data of length {}".format(len(data)))
        print("RMS of data is: {}".format(calc_rms(data)))
        global recv_data
        recv_data = data
    else:
        print("Error receiving data on channel {} (Is scope in run mode?)".format(channel))

def calc_rms(data):
    sum_squares = 0
    for d in data:
        sum_squares += (d * d)
    return math.sqrt(sum_squares / len(data))

if __name__ == "__main__":
    b = PyOsziButtons
    scope = PyOszi(debug=False)
    scope.request_raw_data(0, callback)
    #Scope communication is asynchronous, give it time to  finish
    sleep(2)
    plt.plot(recv_data)
    plt.grid()
    plt.show()
    scope.close()
```

**Comment by ArrestedLightning** [comment]
Thanks for the report.  I've updated raw_data.py to use a Python queue to transfer data to the main thread.
